from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MSMERecord:
    id: str
    name: str
    sector: str
    location: str
    loan_request: str
    gst_filing_timeliness: float
    gst_bank_reconciliation: float
    upi_monthly_inflow_lakh: float
    upi_volatility: float
    bank_avg_balance_lakh: float
    bank_negative_days: int
    epfo_employee_count: int
    epfo_continuity: float
    emi_delay_count_180d: int
    cheque_bounce_count_180d: int
    top_buyer_share: float
    revenue_growth_pct: float
    dso_days: int
    dpo_days: int
    inventory_cycle_days: int
    statement_months: int
    cashflow: tuple[int, ...]


MSME_DATASET: dict[str, MSMERecord] = {
    "suryam": MSMERecord(
        id="suryam",
        name="Suryam Precision Tools",
        sector="Auto components",
        location="Ludhiana, PB",
        loan_request="INR 42L working-capital line",
        gst_filing_timeliness=0.97,
        gst_bank_reconciliation=0.94,
        upi_monthly_inflow_lakh=36.8,
        upi_volatility=0.18,
        bank_avg_balance_lakh=11.6,
        bank_negative_days=1,
        epfo_employee_count=23,
        epfo_continuity=0.92,
        emi_delay_count_180d=0,
        cheque_bounce_count_180d=0,
        top_buyer_share=0.43,
        revenue_growth_pct=16.0,
        dso_days=41,
        dpo_days=33,
        inventory_cycle_days=28,
        statement_months=14,
        cashflow=(45, 51, 56, 61, 58, 67, 72, 78, 82, 85, 91, 96),
    ),
    "meghdoot": MSMERecord(
        id="meghdoot",
        name="Meghdoot Agro Foods",
        sector="Food processing",
        location="Nashik, MH",
        loan_request="INR 28L invoice-backed loan",
        gst_filing_timeliness=0.88,
        gst_bank_reconciliation=0.86,
        upi_monthly_inflow_lakh=18.4,
        upi_volatility=0.32,
        bank_avg_balance_lakh=5.2,
        bank_negative_days=5,
        epfo_employee_count=11,
        epfo_continuity=0.73,
        emi_delay_count_180d=1,
        cheque_bounce_count_180d=0,
        top_buyer_share=0.61,
        revenue_growth_pct=10.0,
        dso_days=56,
        dpo_days=39,
        inventory_cycle_days=46,
        statement_months=9,
        cashflow=(42, 48, 63, 74, 88, 81, 59, 53, 61, 66, 72, 78),
    ),
    "neelkanth": MSMERecord(
        id="neelkanth",
        name="Neelkanth Textiles",
        sector="Textile processing",
        location="Surat, GJ",
        loan_request="INR 35L machinery upgrade",
        gst_filing_timeliness=0.81,
        gst_bank_reconciliation=0.79,
        upi_monthly_inflow_lakh=24.1,
        upi_volatility=0.27,
        bank_avg_balance_lakh=7.8,
        bank_negative_days=3,
        epfo_employee_count=18,
        epfo_continuity=0.84,
        emi_delay_count_180d=1,
        cheque_bounce_count_180d=1,
        top_buyer_share=0.39,
        revenue_growth_pct=7.0,
        dso_days=49,
        dpo_days=37,
        inventory_cycle_days=52,
        statement_months=12,
        cashflow=(50, 53, 55, 54, 57, 62, 65, 63, 68, 70, 71, 75),
    ),
    "vardhan": MSMERecord(
        id="vardhan",
        name="Vardhan Machine Works",
        sector="Industrial tools",
        location="Rajkot, GJ",
        loan_request="INR 18L term loan",
        gst_filing_timeliness=0.74,
        gst_bank_reconciliation=0.71,
        upi_monthly_inflow_lakh=12.3,
        upi_volatility=0.44,
        bank_avg_balance_lakh=3.1,
        bank_negative_days=9,
        epfo_employee_count=8,
        epfo_continuity=0.62,
        emi_delay_count_180d=3,
        cheque_bounce_count_180d=2,
        top_buyer_share=0.67,
        revenue_growth_pct=2.0,
        dso_days=68,
        dpo_days=41,
        inventory_cycle_days=58,
        statement_months=7,
        cashflow=(38, 35, 41, 37, 33, 36, 39, 34, 31, 35, 33, 37),
    ),
    "adya": MSMERecord(
        id="adya",
        name="Adya Packaging",
        sector="Packaging",
        location="Indore, MP",
        loan_request="INR 24L working-capital line",
        gst_filing_timeliness=0.91,
        gst_bank_reconciliation=0.89,
        upi_monthly_inflow_lakh=29.6,
        upi_volatility=0.21,
        bank_avg_balance_lakh=9.7,
        bank_negative_days=2,
        epfo_employee_count=16,
        epfo_continuity=0.88,
        emi_delay_count_180d=0,
        cheque_bounce_count_180d=0,
        top_buyer_share=0.34,
        revenue_growth_pct=13.0,
        dso_days=38,
        dpo_days=30,
        inventory_cycle_days=33,
        statement_months=13,
        cashflow=(52, 55, 58, 61, 60, 64, 68, 71, 74, 76, 80, 84),
    ),
    "kaveri": MSMERecord(
        id="kaveri",
        name="Kaveri Handlooms",
        sector="Textiles",
        location="Erode, TN",
        loan_request="INR 12L inventory loan",
        gst_filing_timeliness=0.85,
        gst_bank_reconciliation=0.8,
        upi_monthly_inflow_lakh=9.8,
        upi_volatility=0.35,
        bank_avg_balance_lakh=2.9,
        bank_negative_days=4,
        epfo_employee_count=6,
        epfo_continuity=0.7,
        emi_delay_count_180d=1,
        cheque_bounce_count_180d=0,
        top_buyer_share=0.48,
        revenue_growth_pct=9.0,
        dso_days=52,
        dpo_days=35,
        inventory_cycle_days=61,
        statement_months=10,
        cashflow=(30, 33, 37, 35, 40, 43, 41, 45, 47, 46, 50, 53),
    ),
    "zenlabs": MSMERecord(
        id="zenlabs",
        name="ZenLabs Diagnostics",
        sector="Healthcare services",
        location="Pune, MH",
        loan_request="INR 55L equipment loan",
        gst_filing_timeliness=0.95,
        gst_bank_reconciliation=0.93,
        upi_monthly_inflow_lakh=41.2,
        upi_volatility=0.15,
        bank_avg_balance_lakh=14.3,
        bank_negative_days=0,
        epfo_employee_count=31,
        epfo_continuity=0.94,
        emi_delay_count_180d=0,
        cheque_bounce_count_180d=0,
        top_buyer_share=0.22,
        revenue_growth_pct=21.0,
        dso_days=29,
        dpo_days=28,
        inventory_cycle_days=18,
        statement_months=16,
        cashflow=(58, 62, 66, 70, 73, 77, 80, 84, 87, 90, 94, 97),
    ),
    "bhoomi": MSMERecord(
        id="bhoomi",
        name="Bhoomi Agro Traders",
        sector="Agri trading",
        location="Guntur, AP",
        loan_request="INR 20L crop-cycle credit",
        gst_filing_timeliness=0.7,
        gst_bank_reconciliation=0.66,
        upi_monthly_inflow_lakh=15.6,
        upi_volatility=0.51,
        bank_avg_balance_lakh=3.8,
        bank_negative_days=8,
        epfo_employee_count=5,
        epfo_continuity=0.55,
        emi_delay_count_180d=2,
        cheque_bounce_count_180d=1,
        top_buyer_share=0.58,
        revenue_growth_pct=4.0,
        dso_days=71,
        dpo_days=44,
        inventory_cycle_days=66,
        statement_months=8,
        cashflow=(28, 41, 55, 62, 48, 33, 27, 31, 44, 52, 39, 30),
    ),
    "rhythm": MSMERecord(
        id="rhythm",
        name="Rhythm Apparel Exports",
        sector="Garments",
        location="Tiruppur, TN",
        loan_request="INR 38L export packing credit",
        gst_filing_timeliness=0.89,
        gst_bank_reconciliation=0.87,
        upi_monthly_inflow_lakh=27.4,
        upi_volatility=0.24,
        bank_avg_balance_lakh=8.1,
        bank_negative_days=2,
        epfo_employee_count=26,
        epfo_continuity=0.86,
        emi_delay_count_180d=0,
        cheque_bounce_count_180d=0,
        top_buyer_share=0.52,
        revenue_growth_pct=11.0,
        dso_days=47,
        dpo_days=36,
        inventory_cycle_days=41,
        statement_months=12,
        cashflow=(46, 49, 53, 57, 55, 60, 63, 67, 65, 70, 73, 77),
    ),
    "sagar": MSMERecord(
        id="sagar",
        name="Sagar Marine Foods",
        sector="Seafood processing",
        location="Kochi, KL",
        loan_request="INR 30L cold-chain loan",
        gst_filing_timeliness=0.83,
        gst_bank_reconciliation=0.78,
        upi_monthly_inflow_lakh=22.7,
        upi_volatility=0.38,
        bank_avg_balance_lakh=6.4,
        bank_negative_days=5,
        epfo_employee_count=19,
        epfo_continuity=0.77,
        emi_delay_count_180d=1,
        cheque_bounce_count_180d=1,
        top_buyer_share=0.63,
        revenue_growth_pct=8.0,
        dso_days=58,
        dpo_days=40,
        inventory_cycle_days=49,
        statement_months=11,
        cashflow=(40, 46, 52, 58, 50, 44, 48, 55, 60, 54, 49, 53),
    ),
    "trident": MSMERecord(
        id="trident",
        name="Trident Electronics",
        sector="Electronics assembly",
        location="Noida, UP",
        loan_request="INR 46L purchase-order finance",
        gst_filing_timeliness=0.93,
        gst_bank_reconciliation=0.9,
        upi_monthly_inflow_lakh=33.9,
        upi_volatility=0.19,
        bank_avg_balance_lakh=10.8,
        bank_negative_days=1,
        epfo_employee_count=21,
        epfo_continuity=0.9,
        emi_delay_count_180d=0,
        cheque_bounce_count_180d=0,
        top_buyer_share=0.41,
        revenue_growth_pct=17.0,
        dso_days=36,
        dpo_days=31,
        inventory_cycle_days=26,
        statement_months=15,
        cashflow=(50, 54, 58, 63, 66, 70, 74, 77, 81, 84, 88, 92),
    ),
    "anvi": MSMERecord(
        id="anvi",
        name="Anvi Ceramics",
        sector="Ceramics",
        location="Morbi, GJ",
        loan_request="INR 26L kiln upgrade loan",
        gst_filing_timeliness=0.78,
        gst_bank_reconciliation=0.74,
        upi_monthly_inflow_lakh=17.2,
        upi_volatility=0.4,
        bank_avg_balance_lakh=4.6,
        bank_negative_days=6,
        epfo_employee_count=13,
        epfo_continuity=0.68,
        emi_delay_count_180d=2,
        cheque_bounce_count_180d=0,
        top_buyer_share=0.55,
        revenue_growth_pct=5.0,
        dso_days=62,
        dpo_days=42,
        inventory_cycle_days=57,
        statement_months=9,
        cashflow=(36, 39, 42, 38, 44, 47, 43, 40, 45, 48, 46, 50),
    ),
}


SCENARIO_EFFECTS = {
    "baseline": {
        "score_offset": 0,
        "data_quality_offset": 0.0,
        "label": "Baseline",
    },
    "thinData": {
        "score_offset": -7,
        "data_quality_offset": -0.18,
        "label": "Thin data",
    },
    "stress": {
        "score_offset": -13,
        "data_quality_offset": -0.08,
        "label": "Stress test",
    },
    "attack": {
        "score_offset": -21,
        "data_quality_offset": -0.12,
        "label": "Attack sim",
    },
}
